#
# This compose file is responsible for bootstrapping entire ecosystem in production mode.
# If you are to develop only a particular component you will be better off with its own compose
# file as it contains only the minimum set of services needed.
#
version: "2"

services:

  mongo:
    image: mongo:3.4.3
    networks:
      appnet:
        ipv4_address: 172.150.1.2
    volumes:
      - ./JustMarriedServer/database/data:/data
      - ./JustMarriedServer/database/dump:/dump
    ports:
      - 27017:27017

  memcached:
    image: memcached:1.4.36
    networks:
      appnet:
        ipv4_address: 172.150.1.4
    ports:
      - 11211:11211

  server:
    image: justmarried/jmserver:production-latest
    ports:
      - 2701:2701
    depends_on:
      - mongo
      - memcached
    networks:
      appnet:
        ipv4_address: 172.150.1.3
    environment:
      - AUTH_REDIRECT_URL=http://localhost:3000/redirect.html?token=%s
      - PROTOCOL=http
      - HOST=localhost
      - PORT=2701
      - DOMAIN=false
      - JWT_SECRET=0a6b944d-d2fb-46fc-a85e-0295c986cd9f
      - MEMCACHED_SERVERS=172.150.1.4:11211
      - MEMCACHED_USERNAME=memcached
      - MEMCACHED_PASSWORD=
      - SESSION_SECRET=secret
      - DB_URL=mongodb://172.150.1.2:27017

  swagger:
    image: swaggerapi/swagger-ui:v3.0.5
    networks:
      appnet:
        ipv4_address: 172.150.1.5
    ports:
      - 5000:8080
    depends_on:
      - server
    environment:
      - API_URL=http://localhost:2701/api/api-docs

  client:
    image: justmarried/jmclient:production-latest
    network_mode: host
    depends_on:
      - server
    environment:
      - SERVER_API_URL=http://localhost:2701/api

networks:

  appnet:
    ipam:
      config:
        - subnet: 172.150.1.0/24
