#
# This compose file is responsible for bootstrapping entire ecosystem in development mode.
# If you are to develop only a particular component you will be better off with its own compose
# file as it contains only the minimum set of services needed.
#
version: "2"

services:

  db:
    image: mongo:3.4.3
    networks:
      backnet:
        ipv4_address: 172.100.1.2
    volumes:
      - ./.tmp/database/data:/data/db
      - ./JustMarriedTools/database/dump:/dump
    ports:
      - 27017:27017

  memcached:
    image: memcached:1.4.36
    networks:
      backnet:
        ipv4_address: 172.100.1.4
    ports:
      - 11211:11211

  server:
    image: justmarried/jmserver:development-latest
    build:
      context: JustMarriedServer
      dockerfile: containers/develop/Dockerfile
    ports:
      - 2701:2701
      - 5858:5858
    volumes:
      - ./JustMarriedServer:/app
    depends_on:
      - db
      - memcached
    networks:
      backnet:
        ipv4_address: 172.100.1.3
    environment:
      - PROTOCOL=http
      - HOST=localhost
      - PORT=2701
      - JWT_SECRET=0a6b944d-d2fb-46fc-a85e-0295c986cd9f
      - MEMCACHED_SERVERS=172.100.1.4:11211
      - MEMCACHED_USERNAME=memcached
      - MEMCACHED_PASSWORD=
      - SESSION_SECRET=secret
      - DB_URL=mongodb://172.100.1.2:27017

  swagger:
    image: swaggerapi/swagger-ui:v3.0.5
    networks:
      backnet:
        ipv4_address: 172.100.1.5
    ports:
      - 5000:8080
    depends_on:
      - server
    environment:
      - API_URL=http://localhost:2701/api/api-docs

  client:
    image: justmarried/jmclient:development-latest
    build:
      context: JustMarriedClient
      dockerfile: containers/develop/Dockerfile
    ports:
      - 80:80
    volumes:
      - ./JustMarriedClient:/app
    depends_on:
      - server
    environment:
      - SERVER_API_URL=http://localhost:2701/api

networks:

  backnet:
    ipam:
      config:
        - subnet: 172.100.1.0/24
